### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by martonbognar** [martonbognar/WebGLMath#2]

**Comment by micskeiz** [comment]
All builds have failed so far on Travis. Why did you not try to fix this?

**Comment by martonbognar** [comment]
@micskeiz The sole reason for the failure was a `console.table` statement in one of the functions. We could have turned off checking for console statements, but that would have only hidden the problem, and removing the statement would (probably) have reduced the fuctionality of the library. We'll try to consult with the original author to find a solution that is acceptable both by him and the JavaScript standard.

**Comment by martonbognar** [comment]
@micskeiz We discussed a solution with the author, #7 is now fixed, the build is passing.
